# Generated by Django 4.2.7 on 2023-11-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('birthday', models.DateField(verbose_name='birthday date')),
                ('tg', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=18)),
                ('about', models.CharField(max_length=400)),
            ],
        ),
    ]
