# Generated by Django 4.2.7 on 2023-11-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_user_course_user_educational_program_user_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
