# Generated by Django 4.2.7 on 2023-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_program',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
    ]
