# Generated by Django 4.2.7 on 2023-11-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_alter_user_about_alter_user_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='educational_program',
        ),
    ]
